apiVersion: v1
kind: Service
metadata:
  name: mern-app-client-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: mern-app-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002