apiVersion: v1
kind: Service
metadata:
  name: mern-app-server-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: mern-app-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008